package com.devhub.scored.features.scoring.data

import android.os.Build
import android.util.Log
import androidx.annotation.RequiresApi
import com.devhub.scored.features.players.data.Player
import com.devhub.scored.features.scoring.domain.BallEvent
import kotlinx.serialization.EncodeDefault
import kotlinx.serialization.ExperimentalSerializationApi
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Remote representation of a single ball-delivery event stored in Supabase.
 *
 * Maps to the `match_events` table.  The table is append-only — rows are never
 * updated or deleted.  The full match state is rebuilt at any point by fetching
 * all rows for a match and replaying them through [com.devhub.scored.features.scoring.domain.ScoreReducer].
 *
 * [id] is auto-generated by Supabase (UUID) and is not sent during insert.  It is
 * populated when reading rows back from the database.  A deterministic composite ID
 * is no longer used because sending a non-UUID `id` value would violate the UUID
 * column constraint on `match_events.id`.
 *
 * [eventIndex] is a 0-based global index within a match.  First-innings events start
 * at 0; second-innings events are offset by the total number of first-innings events
 * so the full match can be sorted by this single column.
 *
 * [payload] contains all delivery details as a typed JSON object (see [BallEventPayload]).
 * Using a JSON payload instead of many nullable columns keeps the schema stable as the
 * [BallEvent] model evolves without requiring new migrations.
 */
@Serializable
data class SupabaseEvent @OptIn(ExperimentalSerializationApi::class) constructor(
    @EncodeDefault(EncodeDefault.Mode.NEVER)
    val id: String? = null,
    @SerialName("match_id") val matchId: String,
    @SerialName("user_id") val userId: String,
    @SerialName("event_index") val eventIndex: Int,
    @SerialName("event_type") val eventType: EventType,
    val payload: BallEventPayload,
    @SerialName("created_at") val createdAt: String = ""
)

/**
 * Typed JSON payload for a single delivery.
 *
 * Fields mirror the columns of [BallEventEntity] so the same flattening logic can
 * be reused for both local Room storage and remote Supabase storage.  All nullable
 * fields are only populated when the corresponding data is present (e.g. dismissal
 * fields are null when [wicket] is false).
 *
 * [inningsNumber] (1 or 2) is included here rather than as a top-level column on
 * [SupabaseEvent] so that the schema stays minimal while still allowing the event
 * log to be split back into first-innings and second-innings lists on load.
 */
@Serializable
data class BallEventPayload(
    val inningsNumber: Int,
    val runsOffBat: Int,
    val wides: Int,
    val noBalls: Int,
    val byes: Int,
    val legByes: Int,
    val wicket: Boolean,
    val countsAsBall: Boolean,
    val dismissedBatterName: String? = null,
    val dismissalType: String? = null,
    val fielderName: String? = null,
    val fielder2Name: String? = null,
    val dismissalBowlerName: String? = null,
    val bowlerName: String? = null,
    val bowlerSourceProfileId: String? = null,
    val strikerName: String? = null,
    val strikerSourceProfileId: String? = null,
    val nonStrikerName: String? = null,
    val nonStrikerSourceProfileId: String? = null,
    val targetIndex: Int? = null,
    val isPenalty: Boolean = false
)

// ---------------------------------------------------------------------------
// Mapping helpers
// ---------------------------------------------------------------------------

/**
 * Convert a local [BallEvent] to a [SupabaseEvent] ready for remote insertion.
 *
 * @param matchId        The local match UUID (shared with the remote `matches.id`).
 * @param userId         The authenticated user's UUID.
 * @param inningsNumber  1 for first innings, 2 for second innings.
 * @param sequenceNumber 0-based position of this event within the innings.
 * @param globalIndex    Globally ordered index within the match (first innings events
 *                       come before second innings events).
 *
 * The [SupabaseEvent.id] field is intentionally omitted (left null) so that Supabase
 * auto-generates the UUID primary key.  Sending a non-UUID value would violate the
 * UUID column constraint on `match_events.id`.
 */
fun BallEvent.toSupabaseEvent(
    matchId: String,
    userId: String,
    inningsNumber: Int,
    sequenceNumber: Int,
    globalIndex: Int
): SupabaseEvent {
    val payload = BallEventPayload(
        inningsNumber = inningsNumber,
        runsOffBat = runsOffBat,
        wides = extras.wides,
        noBalls = extras.noBalls,
        byes = extras.byes,
        legByes = extras.legByes,
        wicket = wicket,
        countsAsBall = countsAsBall,
        dismissedBatterName = dismissalDetail?.batter?.name,
        dismissalType = dismissalDetail?.dismissalType?.name,
        fielderName = dismissalDetail?.fielders?.getOrNull(0)?.name,
        fielder2Name = dismissalDetail?.fielders?.getOrNull(1)?.name,
        dismissalBowlerName = dismissalDetail?.bowler?.name,
        bowlerName = bowler?.name,
        bowlerSourceProfileId = bowler?.sourceProfileId,
        strikerName = striker?.name,
        strikerSourceProfileId = striker?.sourceProfileId,
        nonStrikerName = nonStriker?.name,
        nonStrikerSourceProfileId = nonStriker?.sourceProfileId,
        isPenalty = isPenalty
    )
    val eventType = when {
        isPenalty -> EventType.PENALTY_RUNS
        wicket -> EventType.WICKET
        extras.wides > 0 || extras.noBalls > 0 || extras.byes > 0 || extras.legByes > 0 -> EventType.EXTRA
        runsOffBat > 0 -> EventType.RUN
        else -> EventType.BALL
    }
    return SupabaseEvent(
        matchId = matchId,
        userId = userId,
        eventIndex = globalIndex,
        eventType = eventType,
        payload = payload
    )
}

/**
 * Convert a remote [SupabaseEvent] back to the domain [BallEvent].
 *
 * Reconstructs all nested objects ([Player], [DismissalDetail], [ExtrasBreakdown])
 * from the flattened [BallEventPayload] fields using the same logic as
 * [BallEventEntity.toDomain].
 */
fun SupabaseEvent.toBallEvent(): BallEvent {
    val p = payload
    val extras = ExtrasBreakdown(
        wides = p.wides,
        noBalls = p.noBalls,
        byes = p.byes,
        legByes = p.legByes
    )
    val dismissal: DismissalDetail? = if (p.wicket && p.dismissalType != null && p.dismissedBatterName != null) {
        val type = runCatching { DismissalType.valueOf(p.dismissalType) }.getOrNull()
        if (type != null) {
            val fieldersList = listOfNotNull(
                p.fielderName?.let { Player(name = it) },
                p.fielder2Name?.let { Player(name = it) }
            )
            DismissalDetail(
                batter = Player(name = p.dismissedBatterName),
                dismissalType = type,
                fielders = fieldersList,
                bowler = p.dismissalBowlerName?.let { Player(name = it) }
            )
        } else null
    } else null

    val bowler: Player? = p.bowlerName?.let {
        Player(name = it, sourceProfileId = p.bowlerSourceProfileId)
    }
    val striker: Player? = p.strikerName?.let {
        Player(name = it, sourceProfileId = p.strikerSourceProfileId)
    }
    val nonStriker: Player? = p.nonStrikerName?.let {
        Player(name = it, sourceProfileId = p.nonStrikerSourceProfileId)
    }
    return BallEvent(
        runsOffBat = p.runsOffBat,
        extras = extras,
        wicket = p.wicket,
        dismissalDetail = dismissal,
        countsAsBall = p.countsAsBall,
        bowler = bowler,
        striker = striker,
        nonStriker = nonStriker,
        isPenalty = p.isPenalty
    )
}

// ---------------------------------------------------------------------------
// UNDO_TO_INDEX event helpers
// ---------------------------------------------------------------------------

private const val TAG_REPLAY = "SupabaseEventReplay"

/**
 * Build a [SupabaseEvent] representing an `UNDO_TO_INDEX` command.
 *
 * This event is inserted into the append-only `match_events` log instead of deleting
 * or modifying existing rows.  When the event log is replayed (by the scorer device
 * on reload, or by a viewer via Realtime), [replayInningsEvents] processes this event
 * by truncating the active delivery list to [targetIndex], effectively "un-doing" all
 * deliveries at or after that position.
 *
 * @param matchId        The match UUID.
 * @param userId         The authenticated user's UUID.
 * @param inningsNumber  The innings whose delivery list should be truncated (1 or 2).
 * @param globalIndex    Globally ordered index for this event within the match.
 * @param targetIndex    Desired length of the active delivery list after this undo.
 *                       Must be ≥ 0 and ≤ the current innings delivery count.
 */
fun buildUndoSupabaseEvent(
    matchId: String,
    userId: String,
    inningsNumber: Int,
    globalIndex: Int,
    targetIndex: Int
): SupabaseEvent {
    val payload = BallEventPayload(
        inningsNumber = inningsNumber,
        runsOffBat = 0,
        wides = 0,
        noBalls = 0,
        byes = 0,
        legByes = 0,
        wicket = false,
        countsAsBall = false,
        targetIndex = targetIndex
    )
    return SupabaseEvent(
        matchId = matchId,
        userId = userId,
        eventIndex = globalIndex,
        eventType = EventType.UNDO_TO_INDEX,
        payload = payload
    )
}

/**
 * Replay a single innings' remote event log, respecting `UNDO_TO_INDEX` events.
 *
 * Iterates through [events] in ascending [SupabaseEvent.eventIndex] order.  For each
 * event:
 * - `BALL`          → appended to the active delivery list.
 * - `UNDO_TO_INDEX` → the active list is truncated to [BallEventPayload.targetIndex],
 *                     discarding all deliveries at or beyond that position (but never
 *                     deleting any remote rows).
 *
 * This function is the canonical way to rebuild innings state from the remote log.
 * It is used both during initial load and when processing incremental Realtime events.
 *
 * Edge-cases handled:
 * - [BallEventPayload.targetIndex] null  → undo event is skipped (defensive fallback).
 * - targetIndex out of range (< 0 or > list size) → clamped to valid range.
 *
 * @param events All remote events for a single innings, in any order.
 * @return       The active [BallEvent] list after all undo commands have been applied.
 */
@RequiresApi(Build.VERSION_CODES.VANILLA_ICE_CREAM)
fun replayInningsEvents(events: List<SupabaseEvent>): List<BallEvent> {
    val active = mutableListOf<BallEvent>()
    for (event in events.sortedBy { it.eventIndex }) {
        when (event.eventType) {
            EventType.BALL, EventType.RUN, EventType.EXTRA, EventType.WICKET,
            EventType.PENALTY_RUNS -> active.add(event.toBallEvent())
            EventType.UNDO_TO_INDEX -> {
                val rawTarget = event.payload.targetIndex
                if (rawTarget == null) {
                    Log.w(TAG_REPLAY, "UNDO_TO_INDEX event at index ${event.eventIndex} has null targetIndex — skipping")
                    continue
                }
                val target = rawTarget.coerceIn(0, active.size)
                Log.d(TAG_REPLAY, "Applying undo to index $target (event index ${event.eventIndex})")
                while (active.size > target) active.removeLast()
            }
            else -> Log.w(TAG_REPLAY, "Unknown event type '${event.eventType}' at index ${event.eventIndex} — skipping")
        }
    }
    return active
}
